{% set version = "0.9-3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-biglm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/biglm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/biglm/biglm_{{ version }}.tar.gz
  sha256: 805d483dc58c041f1616267abeb39cecaaf7271a34e90668a5439383bf9a0d58

build:
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('m2w64_fortran') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-dbi                        # [build_platform != target_platform]
  host:
    - r-base
    - r-dbi
  run:
    - r-base
    - r-dbi

test:
  commands:
    - $R -e "library('biglm')"           # [not win]
    - "\"%R%\" -e \"library('biglm')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=biglm
  license: GPL-2.0-or-later
  summary: Regression for data too large to fit in memory
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
