{% set version = '0.9-1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-biglm
  version: {{ version|replace("-", "_") }}

source:
  fn: biglm_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/biglm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/biglm/biglm_{{ version }}.tar.gz
  sha256: e189554913a3b162c8be04e7d0d8143eb4da0fcec56113cb1ce99f42fc22f0fc

build:
  merge_build_host: True  # [win]
  number: 1003
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_fortran') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-dbi
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-dbi

test:
  commands:
    - $R -e "library('biglm')"           # [not win]
    - "\"%R%\" -e \"library('biglm')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=biglm
  license: GPL
  summary: Regression for data too large to fit in memory
  license_family: GPL

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
