appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: azINNAUHkZndmrLrh6X3CGS7GzJE+UETuSso5q/kMC1etls19KHpgSWaQQJnULMdBnJW98fLrKCs/UPUGKwBy3ZmIu172W9+KS/nE9Tp69PRBH7/94hCkwku2HP6pI7CEe1ijwkKVuat5QA/hQEwMlTSgFsadvamytp5Tl9+KcWREhk0Slk5Lah4ozYkLuZW9lKOV49zHK7Y3cLNM9bD2zeRHy8hxHwMdqTZ1lRre0Sv/RQ/yFcjo3XfiLlkaH/P9OJlnLf/bfO/44YZWBL4B5PPAgclbegxArjx0inY8l9PHsPLYrhoZu/LF94uf9DoK/E9eXxwaSMmRCPu6A56lO4Gz3SeDa2f0qgfLIQFy/oJxOz+rvkBqB7HLpcREtceTrskA15g1NKNGzDeWzNUxz11X4rLF8oejhnS1Z+Z6sMICwbomhY7e3/ogZSempgY5755DCJlfreUCIILr4SzlAi/2jKvbxLFRcB+vZpxO7gwg77r+MPB7f8gL5Qu518kd/ZhrnVlQiddH2MLisJ29YUwuqe6enpWsbUQPDSpixcvCU996iVlLl6EuRN9gVyj2BInIHH7gP6gKmMRfEcaBxjEPZEj1iEkoHwgZlTUJ5phfNre9+H+MWINrGuJQg2YIa1ziFb7KBncJrIZ/opiOvlJBBd7xNswY+DB08t9z9I=
