travis:
  secure:
    BINSTAR_TOKEN: Jgg0AXovTbwHNV0LH3S/+msVf6TTex+txtRLsvju8pIKFg7xlUibQfdLR2tzy7hI+QiSveRXO+BSa+64zbKrYW31rmuUC3zwnRqLxuR5Lqy06EWR/0yajrqremjLDCx1waqA/bS0N46eZFWy4fccE3VGZ6v7CRijlmjvZjPe5hMqL+q4pg5fwwlmP3ULaY3GtvMyLoqxTzSLf8INlYGBFuORISRC6LOAAycL9njoe7NcV5XuSAy9ez88qfet5f3SXYpEJch0ZDBZmb5vugFWwBfWa3S+eoOwlfqRTDU3q6Rrkf5wK+WpVvfaSupxGlRK9DhsGKzMrLUBJjus4iFiZbsKdbQ6xSfYt9OtfTtnTv3vrG2fjCieA5ay5OyKeBpPhpz02ZvUTA2fUpTUPXDO+QkrUeIlxKkWvTsrW1/43a6u0e2RR3Z9SpSbweFenZAZi3BPLVk9Umo6v427zHp+qLIrvbssF3vzsF7+TauNtUbLqtBRWizsOf/6+H0yVfQwFqf8yQx7J9IsBSxiNGHv7ILyXnF7fyqPVQB9w384XnOputyJ7sJcHg3bJQUcehyHckdQ1OnziF1b3r951XhshN4cHF00wzeFyRthAX+QK5sVMpZuDAMwdKurc5OEQ5TaQTPgRkV7z6FFBR/Gk+PGdpFSs40zH3vBEHTczmFNrAo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
