travis:
  secure:
    BINSTAR_TOKEN: oAfdFp+3kLK7NgSLxVQ5p27mD3puMEt2sRXxgUv5RBgMCa6EBDgHUjALP/tN7xdiok2fwccqNF8zU/fZYc5Xb5qJUjftnKPPIs3I75Zv56fBNfJEr9ZMCk+E9+6YYnQJjb9J1YDuoquVs87/vAS6Dnaq7LjC+YXIWgrmYI2X3WSL4GzctWqp66krEaycMsrtlkvE/qHWWH+oNDUPNhSrokzUJqyAVElRfhzda4pU6IA50JvvhwBvmRtQuWMjmAB+P7PWR6tyUYMSVRpGYY1xuItlpUoNW+nbuvZCzi1PflHD3tiB+oDz2/d/HB1wz9+j1tiScaBjP2nO1DTBYLgvUp4tJgrqDF7IIAGUPRyDT4+ESTLC9tKVikvP+M3LWNSomRwSNLovT735q5fNmgQ2g95QSLhPC2GnGnuWOoVci2AxN+Qg8nK9+v9fQRMnvsCIiWx2RzPFRyYtQbgCa0snmyJiQ2o31HxzxGK5ji6ofbcUi+EhYtQeun2UTEbRtBM1f4bqRNcz5mnm5XqozWidm8ooSbF5wJYfVkUP9fHO/vCCHaRpPajfDpoSCzCEbQEEIYauq3ZpmGkboxI9VdMYyx0Svl0hX1qgypy2SYXQYK1WNnRsnOfZMFeUSLk8tG4bcbXPNQnNqS7oMqWuzNJdtJ8BDFhKBw9y2PDvKFd7/Zk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
