travis:
  secure:
    BINSTAR_TOKEN: NgF0sDTYeGdhCqI8/XF3g9fccsm8fA6HlluoM+6GCSM0+tBzeo8AbPyzgVmPs3NEa9VKFMgf8zDnMCmMlPRPKyoyqc6YUMUz9GD26Uo7AmA57fSAzbl0W3rQDIrk1PENO3yIlnyXXVHlYG11fEIlMR7QneKpBgCfRVXOB23SEHK0V3rCRPancBfn5R/o6F4aslMOEULus5GKZeP5l0Um7NPP/rWG9FrKkOnkbTTshbc+a81TxAPxlZ7r4LrdQ88HwSr8NN//JAtNr0RXLx4EWaTHo63TGSVpKPZ5QfDfdRTOImq1v9hihl5TJYbfUN20atGO7CKEfZqoWtK97XRbVti5cLPJisVmJcLvLHoY4eEgBGPpiTXrZ2U9B2CkBxwMcvu1q2eUOMwSPDp81+fqBVXf7DpufWBGKXBU7MXL8CguGgY2Oosz7ZlgRUvrdJf8VG719yYva9a9Zxx7iBt61W7hkVkGJjba9v+GDB1FipyLWUPFr83H8dtC/JFXBYn9FUn67B5w4P0HrJ1QB7bojnDNDdNlrEXfAAFpSKkPKHEcryQj399r5jWCtoUEGM67xRZWgOcidiPoVVIwszpfoYYBGX6iAHwkf092Os6Q7Aava7aCQ4/Z3bSOiOMPLqKraL3+g+d4/8J0xaYBAb57HScfrqUVssVRbPkxKVNcjfw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
