travis:
  secure:
    BINSTAR_TOKEN: c4VP913gNR1Y89fISU5HTSGUBqC05Fm6MnsMxMFpzZUUmaL52FvvLrUicJ7g5ft3/yGi3w2LqPjl+JMHgvDZjOAImQKHkBNTOXs564fhIjjGaMpwQLeNrgsJ0psudwmURq6UUp2gLwnzDDMl8/2CJxQaA0O92Ro+BmAG9yKzSKeKLxza0yM7FfhhYXNdIqqIXX1KCBEyCHhii6rY6ewNlYGTm878exwuLnfE/NlWIR3JAoUs5z5l3AjdyjRnLmXUc75S0U8vPPCAqkDtHgly6BGFyBS5IL50/LL7bZHFdlGSJBl6phnLDr9chiGrLAmFlsCx5v8O/4yJgkdWkKx2sELeCisSIp6S2YaRdVhA9ewPRoxo/HRn1tjNu1ru7cA3qHsd78No8d4kxRWvS1S+vl5Iq6kHYJxxlkVw2xob99SdCwMkP3PUzyWVSxusJzsLSplqf+Awp6XlXVy6M2PhM4/fygf77keWC64UrVQTGjk4Qi0t10swH7nRv7BFzIGI1Sr20ykUqNJy6wFMhLzneLl0qbhj2YkS12jf6dJupcxHCbakPJkdY15U9UZJ8qe41ikwCGwo5cc/zHA2M3MAK3yUzk/1h/tqXxa+lE+6XO/9qGr071FSQMVDuhQET4TG3uBWEPiN8cW6mwpFlY8RYBI+RCx0cf7Ivr6/9cmTNMc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
